In [1]:
import pandas as pd

pd.set_option('display.max_rows', 181)
pd.set_option('display.max_columns', 80)
pd.set_option('display.max_colwidth', 60)

In [2]:
# import
if(True):
    df_inc = pd.read_csv('data/Exp4A/dataframe_complete.csv')
    df_inc['pid'] = df_inc['pid']+100
    df_inc.insert(2, 'structure', 'increasing')

    df_dec = pd.read_csv('data/Exp4B/dataframe_complete.csv')
    df_dec['pid'] = df_dec['pid']+200
    df_dec.insert(2, 'structure', 'decreasing')

    df_con = pd.read_csv('data/Exp4C/dataframe_complete.csv')
    df_con['pid'] = df_con['pid']+300
    df_con.insert(2, 'structure', 'constant')

    dataframe = pd.concat([df_inc, df_dec, df_con])
    dataframe.to_csv('data/EXP4/dataframe_complete.csv', index=False)
else: 
    dataframe = pd.read_csv('data/Exp4/dataframe_complete.csv')

In [3]:
dataframe

,pid,condition,structure,condition_type,beginHit,beginExp,endHit,totalTime,attempts,genEdu,comEdu,age,gender,qUnd,qDes,feedback,cheatTrials,status,numberClicks,rews_exp,rews_exp_total,rews_exp_mean,scores,pa_mean,pa_complete,pa_et
0,100,0,increasing,flowchart,2020-09-23 16:17:06.722939,2020-09-23 16:20:39.203154,NaN,-,1,-,-,-,-,-,-,-,0,6,[],[],0.0,NaN,[],NaN,[],[]
1,101,0,increasing,flowchart,2020-09-23 16:07:04.273675,2020-09-23 16:14:01.115184,2020-09-23 16:19:46.762834,12.3,1,College degree,No,31,Male,"I think so, it seemed to work really well based on my un...",I would tell them that the best course of action is to s...,I really enjoyed this study and found it both challengin...,0,4,"[12, 10, 5, 2, 1, 1, 5, 5, 12, 1]","[10, 26, 45, 46, 47, 47, 43, 43, 14, 47]",368.0,36.8,"[10, 26, 49, 48, 43, 41, 39, 31, 14, 55]",0.7592,"[0.385, 0.538, 0.4, 0.667, 1.0, 1.0, 0.833, 1.0, 0.769, ...","[0, 3.0, 2.501, 0, 0, 0, 0, 0, 0, 0]"
2,102,0,increasing,flowchart,2020-09-23 16:11:43.659499,2020-09-23 16:15:29.122329,2020-09-23 16:19:01.939426,6.9,1,College degree,No,31,female,no it did not make sense,I would just tell them to click randomly,NaN,10,4,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.0,0.0,"[-36, -54, -18, -54, -54, -30, -56, -30, 52, 30]",0.0000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[3.314, 2.797, 2.702, 4.479, 2.783, 2.744, 3.414, 2.382,..."
3,103,0,increasing,flowchart,2020-09-23 16:07:22.506077,2020-09-23 16:17:35.32605,2020-09-23 16:22:22.053401,14.5,2,High school graduate,No,38,Female,Kind of,Click on the nodes and reveal the most lucrative path to...,Very interesting,0,4,"[12, 5, 9, 5, 6, 6, 6, 3, 4, 7]","[26, 47, 47, 43, 42, 42, 42, 45, 44, 21]",399.0,39.9,"[26, 43, 43, 51, 46, 48, 42, 39, 48, 29]",0.6075,"[0.462, 0.5, 0.5, 0.154, 0.857, 0.857, 0.714, 1.0, 0.8, ...","[0, 0, 0, 8.0, 0, 0, 0, 0, 0, 6.0]"
4,104,0,increasing,flowchart,2020-09-23 16:07:05.716785,2020-09-23 16:18:01.607696,2020-09-23 16:27:12.158349,19.8,1,High school graduate,No,28,female,"Near the end, I think I slowly started to understand it ...","If the it's not the highest number, keep clicking until ...",Thank you for allowing me to participate! It was interes...,1,4,"[5, 0, 5, 3, 3, 10, 12, 12, 12, 12]","[55, 0, 49, 41, 1, 42, 36, 42, 36, 42]",344.0,34.4,"[55, 20, 49, 41, -19, 42, 36, 42, 36, 42]",0.2762,"[0.333, 0.0, 0.333, 0.5, 0.0, 0.364, 0.308, 0.385, 0.308...","[0, 2.204, 0, 0, 2.722, 0, 0, 0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,458,1,constant,actionfeedback,2020-09-30 23:27:55.688023,2020-09-30 23:30:51.383771,2020-09-30 23:34:08.112959,6.1,0,High school graduate,No,24,Female,-,-,"Interesting and fun survey, thanks!",0,4,"[1, 3, 1, 1, 1, 8, 5, 1, 9, 2]","[9, 7, 9, 9, 4, -13, 0, 9, 1, 8]",43.0,4.3,"[4, 22, -6, 14, -1, -13, 5, -6, 1, -7]",0.4234,"[0.5, 0.25, 0.5, 0.25, 0.181, 0.778, 0.625, 0.25, 0.5, 0.4]","[0, 0, 0, 3.0, 4.517, 0, 3.0, 3.0, 0, 3.0]"
159,459,1,constant,actionfeedback,2020-09-30 23:24:23.819587,2020-09-30 23:31:08.157447,2020-09-30 23:36:50.371873,12.3,0,College degree,No,51,female,-,-,NaN,0,4,"[3, 1, 1, 1, 2, 7, 3, 2, 2, 1]","[2, 9, 4, 4, 8, 3, 2, 3, 8, 9]",52.0,5.2,"[17, 24, 4, 19, 3, 23, 2, -2, -12, 9]",0.2459,"[0.154, 0.25, 0.333, 0.0, 0.667, 0.222, 0.0, 0.0, 0.333,...","[3.49, 3.0, 2.0, 3.476, 0, 2.0, 3.708, 5.236, 0, 0]"
160,460,1,constant,actionfeedback,2020-09-30 23:26:59.43174,2020-09-30 23:31:40.22758,2020-09-30 23:34:35.721356,7.5,0,College degree,No,28,male,-,-,NaN,0,4,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[4, -1, -1, -1, -1, -1, 4, -1, -1, 4]",5.0,0.5,"[4, 4, -6, -11, -11, 24, 24, 4, 4, 4]",0.1842,"[0.333, 0.167, 0.154, 0.174, 0.127, 0.167, 0.2, 0.182, 0...","[2.0, 5.005, 5.488, 4.75, 6.866, 4.999, 4.0, 4.509, 6.24..."
161,461,1,constant,actionfeedback,2020-09-30 23:06:05.103414,2020-09-30 23:14:45.249453,2020-09-30 23:18:27.740192,11.1,0,College degree,No,34,Female,-,-,Fun.,0,4,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[4, 4, -1, -1, -1, -1, 9, -1, 9, 4]",25.0,2.5,"[-1, 4, -1, 9, -11, 9, 24, -11, -6, 19]",0.2270,"[0.333, 0.138, 0.25, 0.2, 0.174, 0.182, 0.25, 0.16, 0.25...","[2.0, 6.254, 3.0, 4.0, 4.747, 4.491, 3.0, 5.268, 3.0, 2.0]"
162,462,1,constant,actionfeedback,2020-09-30 22:16:52.045835,2020-09-30 22:22:48.976067,2020-09-30 22:26:36.202571,9.6,0,High school graduate,No,57,female,-,-,NaN,0,3,"[6, 12, 6, 7, 5, 3, 5, 6, 1, 9]","[4, -7, -1, 3, 5, 7, 5, 9, 9, 1]",35.0,3.5,"[4, -7, 4, 8, 15, -3, 0, 4, 24, -4]",0.2033,"[0.143, 0.231, 0.0, 0.25, 0.167, 0.25, 0.167, 0.143, 0.5...","[0, 0, 2.509, 0, 0, 0, 0, 0, 0, 2.0]"